// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  datasource: {
    url: env('DATABASE_URL')
  },
  // Para MongoDB no Prisma 7, você pode usar 'accelerateUrl'
  // ou 'adapter' para configurações específicas
});